site_name: Maintenance Documentation

nav:
  - PÃ¡gina Inicial: index.md
  - Creating core tutorial: create_core.md
  - Closing tickets tutorial: closing_ticket.md
  - Testing services: troubleshooting_results.md
  - Code Explanation: code_explanation.md
  - Zabbix Maintenance: zabbix_maintenance.md
theme:
  name: readthedocs
  hljs_languages:
    - python
